# ==============================================================================
FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /opt/deeprank-gnn-esm
COPY . .

RUN uv pip install --system torch --extra-index-url https://download.pytorch.org/whl/cpu && \
  uv pip install --system .

ENTRYPOINT ["deeprank-gnn-esm-predict"]
# ==============================================================================
