# ==============================================================================
ARG CUDA=12.8.0
FROM nvidia/cuda:${CUDA}-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /opt/deeprank-gnn-esm
COPY . .

RUN uv python install 3.11 && \
  uv pip install --system --python 3.11 .

ENTRYPOINT ["deeprank-gnn-esm-predict"]
# ==============================================================================
