# ==============================================================================
FROM continuumio/anaconda3:2024.10-1
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy deeprank-gnn-esm
WORKDIR /opt/deeprank-gnn-esm
COPY . .

# Setup environment and install
RUN conda env create -f environment-cpu.yml -n env && \
  conda clean -afy
ENV PYTHONPATH="/opt/deeprank-gnn-esm/src:$PYTHONPATH"

# Define the entrypoint
ENTRYPOINT ["conda", "run", "-n", "env", "python", "/opt/deeprank-gnn-esm/src/deeprank_gnn/predict.py"]

# ==============================================================================
