name: validate docker build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cpu, gpu]

    steps:
      - uses: actions/checkout@v4

      - run: docker build -f Dockerfile.${{ matrix.variant }} .
