name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test-pip-cpu:
    name: test (pip, cpu)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install torch (cpu-only)
        run: pip install torch --extra-index-url https://download.pytorch.org/whl/cpu

      - name: install package with dev dependencies
        run: pip install ".[dev]"

      - name: run tests
        run: >-
          pytest --cov
          --cov-report xml:coverage.xml
          --cov-append
          -vv
          --hypothesis-show-statistics

      - uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  test-conda-gpu:
    name: test (conda, gpu)
    needs: test-pip-cpu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: deeprank-gnn-esm-gpu
          environment-file: environment-gpu.yml
          auto-activate-base: false

      - name: install deeprank-gnn-esm
        run: pip install .

      - name: install test dependencies
        run: pip install pytest hypothesis

      - name: run tests
        run: >-
          pytest
          -vv
          --hypothesis-show-statistics
