name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          cache-dependency-glob: "pyproject.toml"

      - name: install package with dev dependencies
        run: uv pip install --system ".[dev]"

      - name: run tests
        run: >-
          pytest --cov
          --cov-report xml:coverage.xml
          --cov-append
          -vv
          --hypothesis-show-statistics

      - uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  build-docker:
    name: test if docker is buildable
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cpu, gpu]

    steps:
      - uses: actions/checkout@v4

      - run: docker build -f Dockerfile.${{ matrix.variant }} .
